# $OpenBSD: Makefile,v 1.11 2014/03/21 15:12:38 jasper Exp $

COMMENT =		minimal try/catch with proper localization of $$@

MODULES =		cpan
DISTNAME =		Try-Tiny-0.22
CATEGORIES =		devel

MAINTAINER =		Cesare Gargano <gar@plusiagamma.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

CPAN_AUTHOR =		DOY


TEST_DEPENDS =		devel/p5-Sub-Name>=0 \
			sysutils/p5-Capture-Tiny>=0.12

.include <bsd.port.mk>
