# $OpenBSD $

COMMENT =		various utility functions

MODULES =		cpan
DISTNAME =		Data-Munge-0.093
CATEGORIES =		devel

MAINTAINER =		Cesare Gargano <gar@plusiagamma.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

TEST_DEPENDS =		devel/p5-Test-Warnings

CPAN_AUTHOR =		MAUKE

.include <bsd.port.mk>
