# $OpenBSD $

COMMENT =		produce tied (and other) separate but combined variables

MODULES =		cpan
DISTNAME =		IO-TieCombine-1.004
CATEGORIES =		devel

MAINTAINER =		Cesare Gargano <gar@plusiagamma.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
