# $OpenBSD $

COMMENT =		return across multiple call levels

MODULES =		cpan
DISTNAME =		Return-MultiLevel-0.04
CATEGORIES =		devel

MAINTAINER =		Cesare Gargano <gar@plusiagamma.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

BUILD_DEPENDS =		${RUN_DEPENDS}
RUN_DEPENDS =		devel/p5-Data-Munge

TEST_DEPENDS =		devel/p5-Test-Fatal

CPAN_AUTHOR =		MAUKE

.include <bsd.port.mk>
