# $OpenBSD $

COMMENT =	compile a log format string to perl-code

MODULES =	cpan
DISTNAME =	Apache-LogFormat-Compiler-0.32
CATEGORIES =	www

MAINTAINER =	Cesare Gargano <gar@plusiagamma.org>

CONFIGURE_STYLE =	modbuild

# Perl
PERMIT_PACKAGE_CDROM =	Yes

TEST_DEPENDS =	devel/p5-Test-MockTime

.include <bsd.port.mk>
